services:
  db-postgres-api-diagnosis:
    image: postgres:latest
    container_name: db-postgres-api-diagnosis
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diagnosis
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hackathon-fiap

  app-api-diagnosis:
    build: .
    image: welderessutti/api-diagnosis:latest
    container_name: app-api-diagnosis
    ports:
      - "8082:8080"
    depends_on:
      db-postgres-api-diagnosis:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db-postgres-api-diagnosis:5432/diagnosis"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
      SPRING_RABBITMQ_USERNAME: "rabbitmq"
      SPRING_RABBITMQ_PASSWORD: "rabbitmq"
      SPRING_RABBITMQ_HOST: "broker-rabbitmq"
    networks:
      - hackathon-fiap

networks:
  hackathon-fiap:
    external: true
